### ISSUE TITLE
System crash

### ISSUE THREAD

**Issue by TecWebTP** [ChuckBell/MySQL_Connector_Arduino#11]
Hello my name is Marcio.
I've been trying to send data with this library along with an MEGA 2560 arduino.
I get a first shipment, but on the second attempt it blocks the arduino because it can not empty the buffer.
I would like a little help if possible!
My email: tecweb07@gmail.com
Thank you!

**Comment by TecWebTP** [comment]
#include <SPI.h>
#include <Ethernet2.h>
#include <MySQL_Connection.h>
#include <MySQL_Cursor.h>
#include <Wire.h>                                                           
#include <OneWire.h>                                                        
#include <DallasTemperature.h>
#include <avr/pgmspace.h>

  byte MAC[] = { 0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED };
  byte HOST[]= {192,168,20,150};
  byte MASK[]= {255,255,255,0};
  byte GATE[]= {192,168,20,1};
  
IPAddress server_addr(000,000,225,122);  
char user[] = "myuser";              
char password[] = "mypass";        

char INSERT_TEMP[] = "INSERT INTO teste_arduino.temperatura(data,hora,pendulo,temp_1,temp_2,temp_3,temp_4,temp_5,temp_6,temp_7,temp_8,temp_9,temp_10,temp_11,temp_12,temp_13,temp_14) VALUES (NOW(),CURTIME(),%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d)";  
char query[128];
char INSERT_TEMP_2[] = "INSERT INTO teste_arduino.temperatura(data,hora,pendulo,temp_1,temp_2,temp_3,temp_4,temp_5,temp_6,temp_7,temp_8,temp_9,temp_10,temp_11,temp_12,temp_13,temp_14,temp_15,temp_int) VALUES (NOW(),CURTIME(),%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d)";
char query_2[128];
EthernetServer server(8090);
EthernetClient client;
MySQL_Connection conn((Client *)&client);
 int resetPin = 12;
 
 #define ONE_WIRE_BUS_1 25 
 #define ONE_WIRE_BUS_2 27
 #define ONE_WIRE_BUS_3 29
 #define ONE_WIRE_BUS_6 23
  
  OneWire oneWire_1(ONE_WIRE_BUS_1);  
  OneWire oneWire_2(ONE_WIRE_BUS_2);  
  OneWire oneWire_3(ONE_WIRE_BUS_3);  
  OneWire oneWire_6(ONE_WIRE_BUS_6); 
  
  DallasTemperature pendulo_1(&oneWire_1);
  DallasTemperature pendulo_2(&oneWire_2);
  DallasTemperature pendulo_3(&oneWire_3);
  DallasTemperature sensor_int(&oneWire_6);
   
 DeviceAddress S_1 = {0x28, 0xFF, 0x88, 0x08, 0xA1, 0x15, 0x03, 0x0D};
 DeviceAddress S_2 = {0x28, 0xFF, 0xA8, 0x05, 0xA1, 0x15, 0x03, 0x68};
 DeviceAddress S_3 = {0x28, 0xFF, 0xD8, 0x07, 0xA1, 0x15, 0x03, 0x02};
 DeviceAddress S_4 = {0x28, 0xFF, 0xD4, 0x33, 0xA1, 0x15, 0x03, 0x65};
 DeviceAddress S_5 = {0x28, 0xFF, 0x6C, 0x33, 0xA1, 0x15, 0x03, 0x14};
 DeviceAddress S_6 = {0x28, 0xFF, 0xFC, 0x32, 0xA1, 0x15, 0x03, 0x2C};
 DeviceAddress S_7 = {0x28, 0xFF, 0xDA, 0x06, 0xA1, 0x15, 0x03, 0x0E};
 DeviceAddress S_8 = {0x28, 0xFF, 0x3A, 0x42, 0xA3, 0x15, 0x01, 0xC9};
 DeviceAddress S_9 = {0x28, 0xFF, 0x1E, 0x06, 0xA1, 0x15, 0x03, 0x33};
 DeviceAddress S_10 = {0x28, 0xFF, 0x5E, 0x1C, 0xA1, 0x15, 0x03, 0xF9};
 DeviceAddress S_11 = {0x28, 0xFF, 0x21, 0x3E, 0xA1, 0x15, 0x03, 0x8C};
 DeviceAddress S_12 = {0x28, 0xFF, 0x6D, 0x4F, 0xA3, 0x15, 0x01, 0x90};
 DeviceAddress S_13 = {0x28, 0xFF, 0xB3, 0x11, 0xA1, 0x15, 0x03, 0x52};
 DeviceAddress S_14 = {0x28, 0xFF, 0xEF, 0x07, 0xA1, 0x15, 0x03, 0xD7};
  
 DeviceAddress S_15 = {0x28, 0xFF, 0xE0, 0x32, 0xA1, 0x15, 0x03, 0x71};
 DeviceAddress S_16 = {0x28, 0xFF, 0xD0, 0x50, 0xA3, 0x15, 0x01, 0x91};
 DeviceAddress S_17 = {0x28, 0xFF, 0xF0, 0x10, 0xA1, 0x15, 0x03, 0x7A};
 DeviceAddress S_18 = {0x28, 0xFF, 0xA8, 0x65, 0xA1, 0x15, 0x03, 0xF8};
 DeviceAddress S_19 = {0x28, 0xFF, 0xDC, 0x4F, 0xA3, 0x15, 0x01, 0x12};
 DeviceAddress S_20 = {0x28, 0xFF, 0x22, 0x32, 0xA1, 0x15, 0x03, 0xD0};
 DeviceAddress S_21 = {0x28, 0xFF, 0x2E, 0x16, 0xA1, 0x15, 0x03, 0x8F};
 DeviceAddress S_22 = {0x28, 0xFF, 0xE1, 0x3E, 0xA3, 0x15, 0x01, 0x5D};
 DeviceAddress S_23 = {0x28, 0xFF, 0x51, 0x11, 0xA1, 0x15, 0x03, 0x0B};
 DeviceAddress S_24 = {0x28, 0xFF, 0x69, 0x05, 0xA1, 0x15, 0x03, 0x87};
 DeviceAddress S_25 = {0x28, 0xFF, 0xE7, 0x06, 0xA1, 0x15, 0x03, 0x66};
 DeviceAddress S_26 = {0x28, 0xFF, 0xE7, 0x15, 0xA1, 0x15, 0x03, 0xD6};
 DeviceAddress S_27 = {0x28, 0xFF, 0x57, 0x14, 0xA1, 0x15, 0x03, 0x16};
 DeviceAddress S_28 = {0x28, 0xFF, 0x8F, 0x1B, 0xA1, 0x15, 0x03, 0xEC};
  
  DeviceAddress S_29 = { 0x28, 0xFF, 0x90, 0x42, 0x65, 0x15, 0x01, 0xC5 };           //ROM Sensor 29
  DeviceAddress S_30 = { 0x28, 0xFF, 0xF0, 0x84, 0x4E, 0x04, 0x00, 0xC7 };           //ROM Sensor 30 
  DeviceAddress S_31 = { 0x28, 0xFF, 0x52, 0x43, 0x65, 0x15, 0x03, 0x57 };           //ROM Sensor 30
  DeviceAddress S_32 = { 0x28, 0xFF, 0xD2, 0x3F, 0x65, 0x15, 0x03, 0x26 };           //ROM Sensor 31 
  DeviceAddress S_33 = { 0x28, 0xFF, 0x32, 0x18, 0x65, 0x15, 0x02, 0x54 };           //ROM Sensor 32
  DeviceAddress S_34 = { 0x28, 0xFF, 0xDA, 0x3D, 0x65, 0x15, 0x01, 0xA3 };           //ROM Sensor 33
  DeviceAddress S_35 = { 0x28, 0xFF, 0xC6, 0x45, 0x65, 0x15, 0x01, 0x4A };           //ROM Sensor 34
  DeviceAddress S_36 = { 0x28, 0xFF, 0xBE, 0xED, 0x51, 0x14, 0x00, 0x76 };           //ROM Sensor 35
  DeviceAddress S_37 = { 0x28, 0xFF, 0xC1, 0x7E, 0x65, 0x15, 0x02, 0x25 };           //ROM Sensor 29
  DeviceAddress S_38 = { 0x28, 0xFF, 0x85, 0x7D, 0x53, 0x15, 0x03, 0x0A };          //ROM Sensor 30 
  DeviceAddress S_39 = { 0x28, 0xFF, 0x6D, 0x43, 0x53, 0x15, 0x03, 0xB3 };          //ROM Sensor 30
  DeviceAddress S_40 = { 0x28, 0xFF, 0x3D, 0x7D, 0x52, 0x14, 0x00, 0xF6 };          //ROM Sensor 31 
  DeviceAddress S_41 = { 0x28, 0xFF, 0x87, 0x1C, 0x52, 0x14, 0x00, 0x1B };          //ROM Sensor 32
  DeviceAddress S_42 = { 0x28, 0xFF, 0x67, 0x7C, 0x65, 0x15, 0x02, 0x8D };          //ROM Sensor 33
  DeviceAddress S_43 = { 0x28, 0xFF, 0x0F, 0x3E, 0x65, 0x15, 0x01, 0xA7 };   
  
  //Coletar ROM Sensor interno
  DeviceAddress S_44 = {0x28, 0xFF, 0xAF, 0x64, 0xA1, 0x15, 0x03, 0x26};
  float temperatura;                                                                        // variável para calcular a temperatura
  int t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14,t15,t16 = 0;
  int t17,t18,t19,t20,t21,t22,t23,t24,t25,t26,t27,t28,t29,t30,t31,t32 = 0;
  int t33,t34,t35,t36,t37,t38,t39,t40,t41,t42,t43,t44,t45,t46,t47,t48 = 0;
  int t49,t50,t51,t52,t53,t54,t56,t57,t58,t59,t60,t61,t62,t63,t64,t65 = 0;
  int t66,t67,t68,t69,t70,t71,t72 = 0;
  int ROUND, seg=0, seg2=0, min=0,tentativa = 0;
void setup() {
  Serial.begin(115200);
  while (!Serial); 
  Ethernet.begin(MAC,HOST,MASK,GATE);
  Serial.println(F("Inicializando Leitura..."));
    delay(500);
      pendulo_1.begin();               //Inicializa o pendulo 1
      pendulo_1.setResolution(S_1, 10);
      pendulo_1.setResolution(S_2, 10); 
      pendulo_1.setResolution(S_3, 10); 
      pendulo_1.setResolution(S_4, 10); 
      pendulo_1.setResolution(S_5, 10); 
      pendulo_1.setResolution(S_6, 10); 
      pendulo_1.setResolution(S_7, 10); 
      pendulo_1.setResolution(S_8, 10);
      pendulo_1.setResolution(S_9, 10);
      pendulo_1.setResolution(S_10, 10); 
      pendulo_1.setResolution(S_11, 10); 
      pendulo_1.setResolution(S_12, 10);
      pendulo_1.setResolution(S_13, 10); 
      pendulo_1.setResolution(S_14, 10);
      
      pendulo_2.begin(); 
      pendulo_2.setResolution(S_15, 10);
      pendulo_2.setResolution(S_16, 10); 
      pendulo_2.setResolution(S_17, 10); 
      pendulo_2.setResolution(S_18, 10); 
      pendulo_2.setResolution(S_19, 10); 
      pendulo_2.setResolution(S_20, 10); 
      pendulo_2.setResolution(S_21, 10); 
      pendulo_2.setResolution(S_22, 10);
      pendulo_2.setResolution(S_23, 10);
      pendulo_2.setResolution(S_24, 10); 
      pendulo_2.setResolution(S_25, 10); 
      pendulo_2.setResolution(S_26, 10);
      pendulo_2.setResolution(S_27, 10); 
      pendulo_2.setResolution(S_28, 10);
      
      pendulo_3.begin();
      pendulo_3.setResolution(S_29, 10);
      pendulo_3.setResolution(S_30, 10); 
      pendulo_3.setResolution(S_31, 10); 
      pendulo_3.setResolution(S_32, 10); 
      pendulo_3.setResolution(S_33, 10); 
      pendulo_3.setResolution(S_34, 10); 
      pendulo_3.setResolution(S_35, 10); 
      pendulo_3.setResolution(S_36, 10);
      pendulo_3.setResolution(S_37, 10);
      pendulo_3.setResolution(S_38, 10); 
      pendulo_3.setResolution(S_39, 10); 
      pendulo_3.setResolution(S_40, 10);
      pendulo_3.setResolution(S_41, 10); 
      pendulo_3.setResolution(S_42, 10); 
      pendulo_3.setResolution(S_43, 10); 
      
      sensor_int.begin();
      sensor_int.setResolution(S_44, 10);
      
    IMPRIME_TEMPERATURA();
    GRAVA_DADOS();
}
void loop() {
     captura_tempo();
     if(seg >= 6 ){                   
     seg=0;        
    IMPRIME_TEMPERATURA();
    GRAVA_DADOS();     
     //software_Reset(); 
 }
}
void GRAVA_DADOS(){
    if (conn.connect(server_addr, 3306, user, password)) {
    delay(500);
    MySQL_Cursor *cur_mem = new MySQL_Cursor(&conn);
    sprintf(query, INSERT_TEMP, 1,t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14);             
    cur_mem->execute(query);
    sprintf(query, INSERT_TEMP, 2,t15,t16,t17,t18,t19,t20,t21,t22,t23,t24,t25,t26,t27,t28);             
    cur_mem->execute(query);
    sprintf(query_2, INSERT_TEMP_2, 3,t29,t30,t31,t32,t33,t34,t35,t36,t37,t38,t39,t40,t41,t42,t43,t44);             
    cur_mem->execute(query_2);
    delete cur_mem;
   Serial.println("Dados Enviados com sucesso!.");
  
  }
  else{
    Serial.println("Connection failed.");
     conn.close();
  }
}
void IMPRIME_TEMPERATURA(){
    pendulo_1.requestTemperatures(); //Requisita ou recupara a temperatura do pendulo 
    pendulo_2.requestTemperatures();
    pendulo_3.requestTemperatures();
    sensor_int.requestTemperatures();
    Serial.println("================== Pendulo 1 =========================="); 
    Serial.print("Sensor 1: ");
    t1= pendulo_1.getTempC(S_1);   
    printTemperature(t1);    
    Serial.print("Sensor 2: ");
    t2= pendulo_1.getTempC(S_2);   
    printTemperature(t2);   
    Serial.print("Sensor 3: ");
    t3= pendulo_1.getTempC(S_3);
    printTemperature(t3); 
    Serial.print("Sensor 4: ");
    t4= pendulo_1.getTempC(S_4);
    printTemperature(t4);   
    Serial.print("Sensor 5: ");
    t5= pendulo_1.getTempC(S_5);
    printTemperature(t5); 
    Serial.print("Sensor 6: ");
    t6= pendulo_1.getTempC(S_6);
    printTemperature(t6);  
    Serial.print("Sensor 7: ");
    t7= pendulo_1.getTempC(S_7);
    printTemperature(t7);   
    Serial.print("Sensor 8: ");
    t8= pendulo_1.getTempC(S_8);   
    printTemperature(t8);    
    Serial.print("Sensor 9: ");
    t9= pendulo_1.getTempC(S_9);   
    printTemperature(t9);   
    Serial.print("Sensor 10: ");
    t10= pendulo_1.getTempC(S_10);
    printTemperature(t10); 
    Serial.print("Sensor 11: ");
    t11= pendulo_1.getTempC(S_11);
    printTemperature(t11);   
    Serial.print("Sensor 12: ");
    t12= pendulo_1.getTempC(S_12);
    printTemperature(t12); 
    Serial.print("Sensor 13: ");
    t13= pendulo_1.getTempC(S_13);
    printTemperature(t13);  
    Serial.print("Sensor 14: ");
    t14= pendulo_1.getTempC(S_14);
    printTemperature(t14);   
    
    Serial.println("================== Pendulo 2 =========================="); 
    Serial.print("Sensor 1: ");
    t15= pendulo_2.getTempC(S_15);   
    printTemperature(t15);    
    Serial.print("Sensor 2: ");
    t16= pendulo_2.getTempC(S_16);   
    printTemperature(t16);   
    Serial.print("Sensor 3: ");
    t17= pendulo_2.getTempC(S_17);
    printTemperature(t17); 
    Serial.print("Sensor 4: ");
    t18= pendulo_2.getTempC(S_18);
    printTemperature(t18);   
    Serial.print("Sensor 5: ");
    t19= pendulo_2.getTempC(S_19);
    printTemperature(t19); 
    Serial.print("Sensor 6: ");
    t20= pendulo_2.getTempC(S_20);
    printTemperature(t20);  
    Serial.print("Sensor 7: ");
    t21= pendulo_2.getTempC(S_21);
    printTemperature(t21);   
    Serial.print("Sensor 8: ");
    t22= pendulo_2.getTempC(S_22);   
    printTemperature(t22);    
    Serial.print("Sensor 9: ");
    t23= pendulo_2.getTempC(S_23);   
    printTemperature(t23);   
    Serial.print("Sensor 10: ");
    t24= pendulo_2.getTempC(S_24);
    printTemperature(t24); 
    Serial.print("Sensor 11: ");
    t25= pendulo_2.getTempC(S_25);
    printTemperature(t25);   
    Serial.print("Sensor 12: ");
    t26= pendulo_2.getTempC(S_26);
    printTemperature(t26); 
    Serial.print("Sensor 13: ");
    t27= pendulo_2.getTempC(S_27);
    printTemperature(t27);  
    Serial.print("Sensor 14: ");
    t28= pendulo_2.getTempC(S_28);
    printTemperature(t28);  
    
    Serial.println("================== Pendulo 3 =========================="); 
    Serial.print("Sensor 1: ");
    t29= pendulo_3.getTempC(S_29);   
    printTemperature(t29);    
    Serial.print("Sensor 2: ");
    t30= pendulo_3.getTempC(S_30);   
    printTemperature(t30);   
    Serial.print("Sensor 3: ");
    t31= pendulo_3.getTempC(S_31);
    printTemperature(t31); 
    Serial.print("Sensor 4: ");
    t32= pendulo_3.getTempC(S_32);
    printTemperature(t32);   
    Serial.print("Sensor 5: ");
    t33= pendulo_3.getTempC(S_33);
    printTemperature(t33); 
    Serial.print("Sensor 6: ");
    t34= pendulo_3.getTempC(S_34);
    printTemperature(t34);  
    Serial.print("Sensor 7: ");
    t35= pendulo_3.getTempC(S_35);
    printTemperature(t35);   
    Serial.print("Sensor 8: ");
    t36= pendulo_3.getTempC(S_36);   
    printTemperature(t36);    
    Serial.print("Sensor 9: ");
    t37= pendulo_3.getTempC(S_37);   
    printTemperature(t37);   
    Serial.print("Sensor 10: ");
    t38= pendulo_3.getTempC(S_38);
    printTemperature(t38); 
    Serial.print("Sensor 11: ");
    t39= pendulo_3.getTempC(S_39);
    printTemperature(t39);   
    Serial.print("Sensor 12: ");
    t40= pendulo_3.getTempC(S_40);
    printTemperature(t40); 
    Serial.print("Sensor 13: ");
    t41= pendulo_3.getTempC(S_41);
    printTemperature(t41);  
    Serial.print("Sensor 14: ");
    t42= pendulo_3.getTempC(S_42);
    printTemperature(t42);  
    Serial.print("Sensor 15: ");
    t43= pendulo_3.getTempC(S_43);
    printTemperature(t43);  
    
    Serial.print("Sensor Interno: ");
    t44= sensor_int.getTempC(S_44);
    printTemperature(t44);
    Serial.println();
 }
 void printTemperature(float temp) {
    ROUND = round(temp);                          //Arredonda o valor da temperatura, Sem casas decimais                                                                       
    if (ROUND == -127)                            //Se deu erro na leitura 
    {
      Serial.println("Erro ao ler temperatura!"); //Escreve que deu erro
    }
    else                                          //Se não
    {
      Serial.print("C: ");                        //Escreve C:
      Serial.println(ROUND);                      //Escreve a temperatura 
    }
  }
void captura_tempo(){
    static unsigned long ult_tempo =0;
       int tempo = millis();
       if(tempo - ult_tempo >= 1000){
         ult_tempo = tempo;
         seg++;
         seg2++;
       }
       if(seg  >=60){
         seg = 0;
         min++;
       }    
  }
  void software_Reset() { //Reinicia do começo, mas não repõe os periféricos e registos
  pinMode(resetPin, OUTPUT);
  delay(1000);               // wait for a second
  digitalWrite(resetPin, LOW);
}

**Comment by ChuckBell** [comment]
Hi,

Observe:

char INSERT_TEMP[] = "INSERT INTO teste_arduino.temperatura(data,hora,pendulo,temp_1,temp_2,temp_3,temp_4,temp_5,temp_6,temp_7,temp_8,temp_9,temp_10,temp_11,temp_12,temp_13,temp_14) VALUES (NOW(),CURTIME(),%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d)";
char query[128];
char INSERT_TEMP_2[] = "INSERT INTO teste_arduino.temperatura(data,hora,pendulo,temp_1,temp_2,temp_3,temp_4,temp_5,temp_6,temp_7,temp_8,temp_9,temp_10,temp_11,temp_12,temp_13,temp_14,temp_15,temp_int) VALUES (NOW(),CURTIME(),%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d)";
char query_2[128];

...

void GRAVA_DADOS(){
  if (conn.connect(server_addr, 3306, user, password)) {
    delay(500);
    MySQL_Cursor *cur_mem = new MySQL_Cursor(&conn);
    sprintf(query, INSERT_TEMP, 1,t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14);
    cur_mem->execute(query);
    sprintf(query, INSERT_TEMP, 2,t15,t16,t17,t18,t19,t20,t21,t22,t23,t24,t25,t26,t27,t28);
    cur_mem->execute(query);
    sprintf(query_2, INSERT_TEMP_2, 3,t29,t30,t31,t32,t33,t34,t35,t36,t37,t38,t39,t40,t41,t42,t43,t44);
    cur_mem->execute(query_2);
    delete cur_mem;
    Serial.println("Dados Enviados com sucesso!.");
  }
  else{
    Serial.println("Connection failed.");
    conn.close();
  }
}

There are two errors that jump out at me:

1) Notice you are connecting each time this method is called but only disconnecting (closing) the connection if there is a failed connection attempt. To fix this, either move the connection to setup() or ensure you are closing the connection each time through the method. Simply add conn.close() inside the successful connection code block. 

Be advised: the connector is anything but lightning fast! Considering how much data you’re transmitting and the frequency of your samples, your sketch may “outrun” the connector’s ability to keep up. Consider slowing your sampling rate or move the connect() call to setup() so it is only done once. 

2) You’re overflowing your query buffers! The buffers defined as query[128] and query_2[128] are too small! The first INSERT string alone is 225 characters long. By the time you convert all 14-15 (15?!?!) integers to characters, you will likely exceed the buffer significantly more! I think you need to either heed my warnings below or change this to 512 bytes (characters). Otherwise, you are likely to encounter strange lockups and other instability.

Now, there are other issues but not related to the connection problem. Consider the following rhetorical (meaning no need to respond to my questions) if you deem it so but I wonder if there could be other problems down the road or perhaps some improvements necessary.

Why are you using two buffers for the queries? Wouldn’t one work for both? Surely it is so (if properly sized). ;)

Why are you storing integers? Given the sampling rate you’ve chosen, I would expect a desire for more accuracy.  

Wow, that’s a lot of sensors! Why are you using so may variables? This seems way too many. Can’t you just get the result from the sensor one-at-a-time? If you must have that many, why not use an array? Same storage, but easier to iterate over. 

Similarly, what are you storing all of the sensor values in a single row of your table? Is it a set of values from a set of sensors? Wouldn’t it make more sense to store them separately, one-per-row? Normalized sensor network databases tend to store them separately to keep the rows short (easier, faster to transmit) and associate a key (typically a surrogate AUTO_INCREMENT) as well as an event_id to group the sensor readings. 

I also must question the frequency or sample rate. A sample rate of 1 or a few seconds for temperature could be considered excessive. That is, the sample rate should be designed to retrieve samples at a frequency that meets the observational requirements and no more. For example, sampling temperature in a controlled environment every second would generate a tremendous amount of wasted data. However, if you are trying to plot or analyze temperature fluctuations to pinpoint a moment in time in an uncontrolled environment when the change occurred, then perhaps a higher sampling rate is necessary. Finally, sampling rate should also consider the accuracy of the sensors involved. The Dallas 1-wire sensors are not professional, scientific-grade sensors and have a rather high, non-linear error rate. See the datasheet for confirmation for your choice of sensor.

Also, why are you using NOW() and CURTIME() when a TIMESTAMP column will do exactly the same thing? Or are you trying to group the sensors to a specific datetime?

You could be transmitting more data than necessary over the wire. If you are including all columns in the table for each insert, the following statements are identical but one is transmitting fewer bytes.

INSERT INTO teste_arduino.temperatura(data,hora,pendulo,temp_1,temp_2,temp_3,temp_4,temp_5,temp_6,temp_7,temp_8,temp_9,temp_10,temp_11,temp_12,temp_13,temp_14) VALUES (NOW(),CURTIME(),%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d)

INSERT INTO teste_arduino.temperatura VALUES (NOW(),CURTIME(),%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d)

Finally, I dare say your choice of the Mega board is an absolute must. There is a lot of data being used in this sketch. I wonder if this could be reduced by sampling and storing one sensor at a time using a static array stored in program memory (hint: see PROGMEM).

Hope this helps,

Dr. Bell

**Comment by TecWebTP** [comment]
Hi Dr. Bell!
Thanks for helping me!

Actually only with the increase of the buffer, the system did not lock anymore.
But it is certainly possible to improve this code.
I'd like your help if you're up for it.

I'll explain to you why this code was initially made:

1) I am using this system in a system of thermometry in grain silos, they are huge silos, with capacity of 4500 tons of grains and in that space, among the grains was developed pendulums with 26m of height and every 2 meters there is a sensor DS18b20; In each bin contains 5 pendulums of sensors.
That's why so many sensors. And it takes an hourly reading.

2) Note that in the example there are only 3 pendulums with sensors (one with 15 Sensors and 2 with 14 Sensors each). The system would still need to support 2 more pendulums with 14 sensors each.

3) I am using fields (date and time) -> NOW () and CURTIME (), just to make it easier to display the data to the end user, since there is a PHP system that searches the database to view the user.
This could certainly be with just one field and in PHP use explode () to mount a cleaner view.

4) As for developing a matrix to improve the code, that's where you could help me. My biggest question would be regarding the matrix to reduce this code.

And feel free to use my example if it is useful to you.

Thanks again:
Thank you Dr. Bell!

**Comment by ChuckBell** [comment]
Hi. Sorry, this one fell through the cracks. I lost a bunch of emails week before last and this must've been one of them. Send me an email to d r c h a r l e s b e l l at g m a i l dot c o m. I'll try to reply this week.
