### ISSUE TITLE
Azure Database for MySQL server

### ISSUE THREAD

**Issue by hervema** [ChuckBell/MySQL_Connector_Arduino#124]
Hello, I'm trying to use your great library with Azure Database for MySQL server. I know the hostname approach, but I can retrieve the IP. However, despite a lot of research and testing, I can't connect (the connection works very well with MySQL Workbench for example and I'm able to connect to a local MySQL server on a Rasberry). 

So, before trying to go further in the research, I would like to know if your library is able to connect to this kind of resource on the Cloud?

Thanks in advance,

Regards

**Comment by hervema** [comment]
additional info : I get Error: 44 = tive_password .... !

**Comment by ChuckBell** [comment]
Aha. You need to turn on native password authentication. See
https://dev.mysql.com/doc/refman/8.0/en/native-pluggable-authentication.html
.

**Comment by hervema** [comment]
It seems the case for the user I use for (hervema)

![PbAzureMySQL](https://user-images.githubusercontent.com/23320512/74412074-f3973a00-4e3c-11ea-939e-040c97e4aa72.jpg)

I did test with different MYSQL version (5.6, 5.7 and 8.0) :-(

**Comment by ChuckBell** [comment]
Ok, can you tell me what version of MySQL you're trying to connect to in Azure? Can you connect to that server from the same WiFi (or Ethernet) subnet as your Raspberry Pi?

**Comment by hervema** [comment]
For Azure, I did tests with MySQL 5.6, 5.7 and 8.0. Same result for all versions.

Yes, It's the same Ethernet network to address that Azure server as my Rasberry Pi (for which I can access locally, with a direct local IP (192.168.0...) or thru a dyndns address, for all that's works fine).

**Comment by ChuckBell** [comment]
If you've used a variety of MySQL versions and still can't connect, then it is reasonable to start looking at your network connection or the security requirements of the cloud provider. For example, check to ensure you don't need a VPN or some other pre-connection procedure before connecting. Also, I'd try using the mysql client and enter the same connection information in your sketch (host IP, port, user, passwd) and if that works, we're back to some incompatibility with the MySQL version. If it doesn't work, try working out that issue and when fixed, try the connector again.

What about firewalls? Any in the way? All ports open? Are you using the correct port?

If none of that works, you may want to consider sending data via MQTT messages. Yes, you can do that in that cloud vendor (check it and see).

However, back to the version. I looked at the Azure MySQL product and I cannot determine which version it is. If you can connect to it, please execute this command and send/post the result:

SELECT @@VERSION;

I ask again because I'm reading that the product from Azure may not be a "standard" MySQL release. Best to check it, please. I would but I haven't an account.

**Comment by ChuckBell** [comment]
Closed due to inactivity.
