### ISSUE TITLE
SELECT statement is  returning NULL

### ISSUE THREAD

**Issue by yasar-git** [ChuckBell/MySQL_Connector_Arduino#168]
I am trying to get DB data using  SELECT. But Unfortunately, I am always getting NULL even though I have data in my database.  The following is my code ( i didn't include the server details and include statements).  If I include all the codes inside the loop instead of a function like void check_parameter(), everything works !. But why it isn't working when it is inside a function? [link to Arduino Forum!](https://forum.arduino.cc/index.php?topic=735045.new#new)

```
int device_id = 1;
String Parameter[3] = {"one", "two", "three"};

EthernetClient client;
MySQL_Connection conn((Client *)&client);

const char QUERY_PARA[] = "SELECT ref_time, val_first, val_second  FROM test_db.test_table WHERE Id=  %lu;";
char query[128];

void setup()
{
    Serial.begin(115200);
    while (!Serial);
    Ethernet.begin(mac_addr);   
}

void loop()
{
    Serial.println("inside the loop....");
    delay(10000);
    check_parameter();
}


void check_parameter()
{
  if (conn.connect(server_addr, 3306, user, password))
    {
        Serial.println("calling the check_para....");
        delay(5000);
       
        MySQL_Cursor *cur_mem = new MySQL_Cursor(&conn);
        sprintf(query, QUERY_PARA, device_id);

        cur_mem->execute(query);
        column_names *cols = cur_mem->get_columns();

        Serial.println();
        row_values *row = NULL;

        do
        {
            row = cur_mem->get_next_row();
            if (row != NULL)
            {
              // here is the problem. the row is always NULL! I dunno why ??????--------------------------------------

                Parameter[0] = String(row->values[0]);
                Parameter[1] = String(row->values[1]);
                Parameter[2] = String(row->values[2]);
               
                cur_mem->free_row_buffer();
            }
        } while (row != NULL);
        cur_mem->free_columns_buffer();
        delete cur_mem;
       
        Serial.println("printing parameters");
        Serial.println(Parameter[0]);
        Serial.println(Parameter[1]);
        Serial.println(Parameter[2]);

        conn.close();
    }
    else
    {
        Serial.println("Connection failed.");
    }   
}
```

**Comment by ChuckBell** [comment]
Ok, there are two problems here. You're not getting results because the query isn't what you think it is. You have the wrong specifier in the format string. Also, the data type you're using for device_id is integer.

Observe by running this code:

int device_id = 1;
const char QUERY_PARA[] = "SELECT ref_time, val_first, val_second  FROM test_db.test_table WHERE Id= %lu;";
const char QUERY_PARA1[] = "SELECT ref_time, val_first, val_second  FROM test_db.test_table WHERE Id=%i";
char query[128];

void setup() {
  Serial.begin(9600);
  while (!Serial);
  Serial.print("Example as written:\n> ");
  sprintf(query, QUERY_PARA, device_id);
  Serial.println(query);
  Serial.print("Example with int specifier:\n> ");
  sprintf(query, QUERY_PARA1, device_id);
  Serial.println(query);
  unsigned long dev_id = 2;
  Serial.print("Example with correct data type and correct specifier:\n> ");
  sprintf(query, QUERY_PARA1, device_id);
  Serial.println(query);
}

void loop() {
}

When you do, you will discover an interesting result:

Example as written:
> SELECT ref_time, val_first, val_second  FROM test_db.test_table WHERE Id= 3087007745;
Example with int specifier:
> SELECT ref_time, val_first, val_second  FROM test_db.test_table WHERE Id=1
Example with correct data type and correct specifier:
> SELECT ref_time, val_first, val_second  FROM test_db.test_table WHERE Id=1

Look at the query as printed in the serial monitor. The first one is with your code. That's not right, is it? The second is an improvement with the correct specifier, and the third fixes both problems. Change your code accordingly and you should see results.

Now, I make it a habit to print the query string to the serial monitor whenever I write a new sketch. Not only will this allow you to see the query string, it will also allow you to copy the code and paste it in a MySQL terminal to test it. Nice, eh?
