### ISSUE TITLE
Connection Failed , only once connection . 

### ISSUE THREAD

**Issue by giuseppelaporta** [ChuckBell/MySQL_Connector_Arduino#22]
Hi Dr. , i have tried to use your libraries to make a connection with my database. 
After a week of problem with SPI (ethernet shield and RFID both connected) i make a connection with the DB. Now after 5 days the project wont connect in DB. It says Connection failed . =( whats the problem? 

I've tried with 
- LAMP server (xubuntu) and connect only 1 times
-XAMPP IN WINDOWS 
-MYSQL COMMUNITY SERVER WITH WORKBENCH 
 and NO connection .

i tried also with the simple example sketch connect.ino in library v 1.1.1 (downloaded with arduino ide) , and connection failed.

Should I modify some parameter in DB? 

PS. I create a user with privileges (bob and pass secret) exactly the same in your manual of MySqlConnector 1.0.4 (i also used this version of library) .

Sorry for my bad english . 

Thank you in advantages

**Comment by ChuckBell** [comment]
Hello,

Since you said it used to work but no longer, I have to ask, "What has changed?"

First, I suggest you follow the troubleshooting steps in the manual. Specifically, use a second computer (not the one running the server) to connect using the credentials from your sketch. If that succeeds, you can focus on your Arduino. If the test fails (as I suspect), then you can focus on what has changed with your server.

Recall, you must have the correct up address for the server, a user account that is permitted to connect, and the proper privileges. Testing the connection with a computer remotely will confirm whether you have everything setup correctly.

Since you are running on Windows, there is another element to consider: the Windows firewall.

Suffice to say, I would not try the Arduino until you can connect to your server remotely with the MySQL client.

If you are still having problems, please tell me the model Arduino, shield, version of MySQL you are using.

One last note. Version 1.04 is the old version of the connector. You should use the newest one available from the library manager, but do that after you can connect to your server remotely with a PC.

Dr. Bell

**Comment by giuseppelaporta** [comment]
Dr. Bell thank you for the tempestive reply.
 
Yesterday i've installed xampp in my Mac, then i create an user (bob) and i grant all privileges a bob.
I Do a % for hostname.
Then 
-i create a new database
-i set privileges in this database 

Try to Connect and all work...
Restart the arduino --> work... after 3 times arduino said connection failed.
Whats the problem in this case ? Remotely with another PC in my network i can log in database with mysql workbench and i can operate in database, do a query and more . 

The connection in database was estabilished with 1.1.1 and 1.0.4 .. only 3/4 times..

**Comment by giuseppelaporta** [comment]
Soru for the waste of time ! The problem was the Ethernet Shield damaged! Thank you for you support. 
Giuseppe
