### ISSUE TITLE
connection with GSM (sim900)

### ISSUE THREAD

**Issue by zahrayousif** [ChuckBell/MySQL_Connector_Arduino#37]

**Comment by ChuckBell** [comment]
Hi,

That sounds like an interesting project. I do not have any specific code 
I can share, but if you Google for the GSM module you're using and 
append it with 'arduino', you should find several examples.

Melding in the MySQL part is where you'll need the manual for the 
connector. But even there I have several example sketches you can use as 
a guide.

If you need specific help, please reach out. In the meantime, since this 
isn't an issue as such, please consider closing it.

Thanks,

Dr. Bell
