### ISSUE TITLE
Esp8266 12 with error: ets Jan  8 2013,rst cause:4, boot mode:(1,7), is looped on the following line: column_names *columns = cur_mem2->get_columns()

### ISSUE THREAD

**Issue by iurilimamarques** [ChuckBell/MySQL_Connector_Arduino#73]
The select on database returned error on the following line: column_names *columns = cur_mem2->get_columns(). I'm using the Esp8266 12. Anything you need, just ask me.

**Comment by ChuckBell** [comment]
Let’s start with your sketch and any output from the console plus a schema
or even sample data.

**Comment by iurilimamarques** [comment]
The output error from console is:

Exception (28):
epc1=0x40202888 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: cont 
sp: 3fff02c0 end: 3fff04d0 offset: 01a0

>>>stack>>>
3fff0460:  00000000 3fff1774 3ffef47c 40202864  
3fff0470:  40107128 00ffffff 40107128 0100a8c0  
3fff0480:  41d00000 41c00000 feefeffe feefeffe  
3fff0490:  00000000 feefeffe feefeffe feefeffe  
3fff04a0:  00000000 00000000 00000001 3ffef4a8  
3fff04b0:  3fffdad0 00000000 3ffef4a0 40206710  
3fff04c0:  feefeffe feefeffe 3ffef4b0 40100710  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(1,6)


 ets Jan  8 2013,rst cause:4, boot mode:(1,6)

wdt reset

The part of error between >>>stack>>> and <<<stack<<< I decipher on Exception decoder that means looping is occurring at line column_names *columns = cur_mem2->get_columns();

**Comment by iurilimamarques** [comment]
and I'm using the library version 1.1.1 from Mysql conector

**Comment by ChuckBell** [comment]
I’d need to see the sketch to help, sorry. You can email it to me.

**Comment by iurilimamarques** [comment]
Ok, sent to your email.

**Comment by JanissaryID** [comment]
im same, please help me

**Comment by JanissaryID** [comment]
i have same problem, please help me

**Comment by ChuckBell** [comment]
First, please notice this issue hasn't been active for almost a year. Second, notice the author PM'ed me directly. Given that, you should consider that this issue was most likely not an issue but a request for help for a specific problem someone was having. Since it is almost a year old, I cannot tell you what the solution is - I don't remember. 

If you are having a similar issue, you can PM directly. I will try to help you, but please do not post to old issues or open a new issue.  

That said, the most common mistake is the query that is executing isn't returning any rows, has an error, or the networking portions of the connector must be modified to work with your installation. PM me your sketch, version of MySQL, version of Arduino, and any other info you can share.
