### ISSUE TITLE
Authentication against MySQL V8+ new authentication protocol fails

### ISSUE THREAD

**Issue by Muller59** [ChuckBell/MySQL_Connector_Arduino#95]
L.S.

First, thank you for an excellent library. i was VERY lost until i found this library.

I am running a MySQL server on WIN7, version 8.0.12.
I am using the latest version of the library 1.2.0a.
When i tried connecting with a valid user and password, i got the error:

Error: 109 = Client does not support authentication protocol requested by server; consider upgrading MySQL client.

It seems V8+ has a a new authentication mechanism not yet supported by the library.

The (temporary?) solution is to change the MySQL user like this.
ALTER USER 'UUUUUU'@'%' IDENTIFIED WITH **mysql_native_password** BY 'PPPPPP';
FLUSH PRIVILEGES;

i found that info here -> https://stackoverflow.com/questions/50093144/mysql-8-0-client-does-not-support-authentication-protocol-requested-by-server

Will the new authentication protocol find its way into your library?

regards,

Rob Muller

**Comment by ChuckBell** [comment]
Hi. Yes, you must use the mysql_native_password authentication plugin. 
The connector does not work with the new plugin. It is also unlikely it 
will any time soon due to the added complexity and lack of support for 
what is needed. I fear adding that code will make the connector too 
large (memory) for most uses.
